- README.md
- examples/example_rt_node.js
- package.json
- src/management-platform/auth.ts
- src/realtime/client.ts
- src/realtime/handlers.ts
Adds `EndOfTranscript` event to node example
Removes `EndOfStream` event as this is a client event sent to the server not an event received by the client
Stops sending `EndOfTranscript` event on the socket `onDisconnect` event as this results in 2 `EndOfTranscript` events being received by the client.
> Fix EndOfTranscript event firing twice and update example

- examples/example_batch.js
- src/batch/client.ts
- tests/index.test.ts
This PR adds support for passing a `fileName` string when calling `transcribe` or `createJob`.
This is to handle the case where a user passes a raw `Blob` as opposed to a `File`. It will also be useful when we add support for `Buffer` or `ReadStream` inputs, which will also lack file name metadata.
> Allow optional file name when creating job

- examples/microphone_nextjs/components/MicSelect.tsx
- examples/microphone_nextjs/pages/index.tsx
- examples/microphone_nextjs/utils/recorder.ts
As suggested at https://github.com/speechmatics/speechmatics-js-sdk/pull/6#discussion_r1325953737
From the React docs:
> Removing unnecessary Effects will make your code easier to follow, faster to run, and less error-prone.
> Sometimes, your components may need to subscribe to some data outside of the React state. This data could be from a third-party library or a built-in browser API ... Although it’s common to use Effects for this, React has a purpose-built Hook for subscribing to an external store that is preferred instead. 
https://react.dev/learn/you-might-not-need-an-effect#subscribing-to-an-external-store
> Another reason to add useSyncExternalStore is when you want to subscribe to some value exposed by the browser that changes over time …
> useSyncExternalStore for audio access in microphone demo

- package.json
Source maps are currently included in published assets, but point to the src directory which is not included.
> Include src in published assets

- packages/real-time-client/models/audio-event-ended.ts
- packages/real-time-client/models/audio-event-started.ts
- packages/real-time-client/package.json
- packages/real-time-client/schema/realtime.yml
- packages/real-time-client/scripts/openapi-transformed.yaml
The schema was incorrect for `AudioEventStarted` and `AudioEventEnded`. This brings them in line with actual API behaviour.
> Fix audio event types

- examples/nextjs/package.json
- examples/nextjs/src/app/flow/Component.tsx
- examples/nextjs/src/app/flow/Controls.tsx
- examples/nextjs/src/lib/audio-hooks.ts
- packages/browser-audio-input-react/README.md
- packages/browser-audio-input-react/package.json
- packages/browser-audio-input-react/rollup.config.mjs
- packages/browser-audio-input-react/src/index.ts
- packages/browser-audio-input-react/tsconfig.json
- packages/browser-audio-input/package.json
- packages/browser-audio-input/rollup.config.mjs
- packages/browser-audio-input/src/index.ts
- pnpm-lock.yaml
Add two new packages based on the microphone selection flow implemented in the portal
- `@speechmatics/browser-audio-input`:
- Contains just the store/singleton class managing audio devices.
- Also provides a minified build in case someone wants to use this in an inline script tag
- `@speechmatics/browser-audio-input-react`:
- React bindings for the above package
- Constrain the types of the main exported hook
- Updated the NextJS example to use the react package
**Note**: Both these packages export only ESM (apart from the raw client which also provides a minified build). My thinking was there are practically 0 CommonJS use cases for browser microphone selection, so I omitted it from the build.
> Add packages for browser input audio device selection

- .github/workflows/ci.yml
- packages/flow-client/package.json
- packages/flow-client/src/client.ts
- packages/flow-client/test/index.test.ts
- pnpm-lock.yaml
- Add logic ensuring if socket closes before the `ConversationStarted` message is received, we give up waiting for it
- Add test
- Add cancellable functionality to timeouts, so the test scripts don't hang on an orphaned promise
- Add error type strings to the `SpeechmaticsFlowError` class, so we can handle different errors differently
- Add the `"ws"` dependency to the `flow-client` package (this was missing before, breaking the Node polyfill)
> Handle premature websocket close

- packages/real-time-client/src/client.ts
Currently impossible to override config to audio format on the real time client. This allows the user to override
> fix(real-time-client): allow user to override audio_format on start

- packages/real-time-client/package.json
Releases the following changes: https://github.com/speechmatics/speechmatics-js-sdk/pull/84
> Bump RT version

- examples/nextjs/src/app/flow/page.tsx
- packages/flow-client-react/package.json
- packages/flow-client/package.json
- packages/flow-client/src/client.ts
- packages/flow-client/src/jitter-buffer.ts
This PR implements fixed-time buffering for incoming TTS audio. The duration of the buffer is determined by the `audioBufferingMs` option.
This option already exists in the SDK, but was previously implemented with a `setTimeout`, which did not guarantee a reliable buffer. This PR changes the underlying logic to calculate based on the **time of the audio itself** rather than delaying from the time the audio is received.
For example, if a buffer time of `500` is specified, the client will buffer 500ms worth of audio before dispatching `"agentAudio"` events. This makes the audio easier to understand in adverse network conditions.
**Note:** The queue is also automatically flushed whenever a `ResponseCompleted` or `ResponseInterrupted` message is received. This is to prevent audio getting …
> Flow client: Implement fixed-time buffering

- packages/browser-audio-input-react/package.json
Set `"type": "module"` for `@speechmatics/browser-audio-input-react`
> `browser-audio-input-react`: Ensure module is loaded as ESM

- examples/nextjs/src/app/flow/Controls.tsx
- examples/nextjs/src/app/flow/Status.tsx
- examples/nextjs/src/app/flow/page.tsx
- examples/nextjs/src/app/real-time/Controls.tsx
- examples/nextjs/src/app/real-time/Output.tsx
- examples/nextjs/src/app/real-time/Status.tsx
- examples/nextjs/src/app/real-time/page.tsx
- examples/nextjs/src/lib/audio-hooks.ts
- examples/nextjs/src/lib/components/AudioVisualizer.tsx
- packages/browser-audio-input-react/README.md
- packages/browser-audio-input-react/package.json
- packages/browser-audio-input-react/src/use-pcm-audio-recorder.tsx
- packages/browser-audio-input/README.md
- packages/browser-audio-input/package.json
- packages/browser-audio-input/src/pcm-recorder.ts
- packages/real-time-client-react/README.md
Creating a visualizer for the audio recorded with `@speechmatics/browser-audio-input-react` is too hard.
This PR updates the packages `@speechmatics/browser-audio-input` and `@speechmatics/browser-audio-input-react` to make it easier for consumers to create audio visualizers based on the recorded audio.
**This is a breaking change**. Major versions for both packages have been bumped.
- Get rid of the `selfManagedAudioContext`. Consumers **must** now pass an `AudioContext` to the `startRecording` function. This is because it's [best to share one `AudioContext` instance per page, according to MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext#:~:text=It%27s%20recommended%20to%20create%20one%20AudioContext%20and%20reuse%20it%20instead%20of%20initializing%20a%20new%20one%2 …
> Add analyser to PCM audio recorder

- packages/real-time-client-react/package.json
- packages/real-time-client/README.md
- packages/real-time-client/package.json
- packages/real-time-client/src/client.ts
- Add `SocketStateChangeEvent` which can be used for hooking into socket state changes
- Remove unused `ConnectionState` type
> Real-time: Extend socket state events with current status

- examples/nodejs/package.json
- examples/nodejs/real-time-file-example.ts
- packages/flow-client/package.json
- packages/flow-client/src/client.ts
- packages/real-time-client-react/package.json
- packages/real-time-client/package.json
- packages/real-time-client/src/client.ts
Currently, the Node real-time example gives a timeout error when streaming files longer than 10 seconds. This is because we call `stopRecognition` when the data is finished streaming, but there is still audio/transcription being processed before the server disconnects.
This PR allows the user to specify `noTimeout`, to disable waiting for an `EndOfTranscript` message, facilitating faster-than-real-time use cases.
Additionally cleaning up error messages and bumping versions of changed packages.
> RT: Add option to disable timeout on `stopRecognition()`

- packages/real-time-client-react/package.json
- packages/real-time-client/models/info.ts
- packages/real-time-client/package.json
- packages/real-time-client/schema/realtime.yml
- packages/real-time-client/scripts/generate-models.sh
- packages/real-time-client/scripts/openapi-transformed.yaml
- Add missing [`concurrent_session_usage`](https://docs.speechmatics.com/rt-api-ref#info) message to spec and types
- Fix openapi generation script
> Update RT spec: Add missing info session variant

- examples/nextjs-real-time-transcription/app/page.tsx
- examples/nextjs-real-time-transcription/components/Output.tsx
- Fix call to `usePCMAudioRecorder` without context
- Fix language display names (broken since `en_ta` was added, which is not ISO compliant)
> Fix broken RT example

- packages/auth/test/index.test.ts
Tests for `@speechmatics/auth` fail for fork PRs, since they don't have access to the necessary API key (nor should they)
Skip the auth tests whenever the `API_KEY` environment variable is not present
> Skip auth tests if API key not set (i.e. if in a fork)

- packages/browser-audio-input-react/package.json
- packages/browser-audio-input/package.json
- packages/browser-audio-input/src/devices.ts
Clean up media stream after prompting for device permission. For more context, see issue: https://github.com/speechmatics/speechmatics-js-sdk/issues/128
> browser-audio-input: cleanup media stream after permission prompt

- packages/browser-audio-input-react/package.json
- packages/browser-audio-input/package.json
- packages/browser-audio-input/src/pcm-recorder.ts
Remove tracks from `mediaStream` in addition to stopping on cleanup. This removes the microphone indicator in Safari after recording stops
> `browser-audio-input`:  Remove tracks from `mediaStream` on cleanup

- packages/real-time-client-react/package.json
- packages/real-time-client/models/TranscriptFilteringConfig.ts
- packages/real-time-client/models/WordReplacementItem.ts
- packages/real-time-client/models/index.ts
- packages/real-time-client/package.json
- packages/real-time-client/schema/realtime.yml
- Add `type: "object"` to all schema items which either:
- have `properties` defined
- are a `oneOf` with variants which have `properties`
- Re-run model generation
> Real-time client: Add missing `type: "object"` to schema items
